"""All game data and player-facing text for the Hero Incremental wiki.

Numbers are copied from the game's config modules (HeroConfig, GameConfig, SystemsConfig, UpgradeConfig,
RuneConfig, MonetizationConfig, SkinConfig, SeasonConfig, LiveConfig, ResearchConfig, TrialsConfig,
TravelConfig, HallConfig, TitleConfig). When the game changes, update the matching section here and run
`python build.py`.
"""

GAME_URL = "https://www.roblox.com/games/75558507087279"

ROLE_COLOR = {"Tank": "var(--tank)", "Damage": "var(--damage)", "Support": "var(--support)"}

# --------------------------------------------------------------------------------------------- heroes
# stats: Difficulty / Survival / Mobility / Damage on a 1-5 scale (as shown in Hero Select)
HEROES = [
    {"id": "Bulwark", "role": "Tank", "c": "#ffc83c", "tag": "Walking fortress",
     "desc": "Heavy armor, a crushing energy hammer, and a barrier that shrugs off anything the bots throw.",
     "stats": {"Difficulty": 2, "Survival": 5, "Mobility": 2, "Damage": 5},
     "passive": ["Plated", "250 health and 20% damage reduction."],
     "weapon": {"name": "Breaker Hammer", "blurb": "Slow, crushing melee swings that cleave every bot in front of you.",
                "perk": "3.4× damage, ignores Armored bot armor, 14-stud reach.", "alt": "Guard",
                "stats": ["3.4× damage", "0.42× fire rate", "7-ray cleave", "14 reach", "Armor pierce"]},
     "ability": {"name": "Barrier", "icon": "Ability_Barrier", "cd": 14, "blurb": "Project a shield: take 75% less damage for 6s."},
     "ult": {"name": "Seismic Slam", "icon": "Ult_SeismicSlam", "blurb": "Slam the ground: a shockwave hits every bot in front of you (10× damage, 30 studs) and stuns them for 2.5s."},
     "perks": {"minor": [["Fortified", "+60 max health."], ["Long Barrier", "Barrier lasts 9s."]],
               "major": [["Long Haft", "Hammer reach 18 studs."], ["Aftershock", "Seismic Slam stuns for 4s and hits 30% harder."]]},
     "tips": ["Stand on the payload cart: nothing in the Main Hall can out-damage your 250 HP and 20% reduction.",
              "Armor pierce makes him the best Armored-bot farmer at Bronze 3.",
              "Hold right-click to Guard (−60% damage taken) while you walk a capture point."]},
    {"id": "Anchor", "role": "Tank", "c": "#46e6d2", "tag": "Siege diver",
     "desc": "A deep-sea salvage diver in pressure armor. Drags bots into reach, holds the line, and makes the siege robot roll faster.",
     "stats": {"Difficulty": 2, "Survival": 5, "Mobility": 2, "Damage": 4},
     "passive": ["Heavy Hauler", "The Siege Push robot rolls 50% faster while you escort it."],
     "weapon": {"name": "Tidebreaker", "blurb": "A heavy chain whip with an anchor hook on the end. Lashes out further than any other melee.",
                "perk": "2.6× damage, 26-stud lash.", "alt": "Guard", "stats": ["2.6× damage", "0.45× fire rate", "3 rays", "26 reach"]},
     "ability": {"name": "Tether", "icon": "Ability_Tether", "cd": 9, "blurb": "Hook the bot you're facing (38 studs), drag it to you and stun it for 1.5s."},
     "ult": {"name": "Undertow", "icon": "Ult_Undertow", "blurb": "Open a whirlpool where you aim (18-stud radius): it drags every bot in and crushes them for 4s."},
     "perks": {"minor": [["Long Chain", "Tether reaches 55 studs."], ["Ballast", "+75 max health."]],
               "major": [["Riptide", "Tether cooldown −40%."], ["Maelstrom", "Undertow is 40% bigger and lasts 6s."]]},
     "tips": ["Undertow piles a whole wave into one spot: pair it with any splash hero in a group.",
              "Heavy Hauler is the fastest way to push the Silver siege robot.",
              "The 26-stud lash hits bots other melee heroes can't reach."]},
    {"id": "Vanguard", "role": "Damage", "c": "#5ac8ff", "tag": "Frontline rifleman",
     "desc": "A disciplined all-rounder with a reliable pulse carbine. Easy to pick up, never out of place. Every player starts with Vanguard.",
     "stats": {"Difficulty": 1, "Survival": 3, "Mobility": 3, "Damage": 3},
     "passive": ["Field Discipline", "Reloads 20% faster."],
     "weapon": {"name": "Pulse Carbine", "blurb": "Balanced full-auto rifle.", "perk": "Reliable at every range.", "alt": "Aim down sights",
                "stats": ["1× damage", "1× fire rate", "Full auto"]},
     "ability": {"name": "Overdrive", "icon": "Ability_Overdrive", "cd": 16, "blurb": "+50% fire rate and instant reload for 5s."},
     "ult": {"name": "Strike Beacon", "icon": "Ult_StrikeBeacon", "blurb": "Call an orbital strike where you aim: 14× damage to every bot in a 16-stud blast."},
     "perks": {"minor": [["Extended Mag", "+50% magazine size."], ["Quickdraw", "Overdrive cooldown −30%."]],
               "major": [["Sustained Overdrive", "Overdrive lasts 8s instead of 5s."], ["Saturation Strike", "Strike Beacon radius +50%."]]},
     "tips": ["Save Strike Beacon for a fresh respawn wave: packed spawns take the full 14×.",
              "Overdrive's instant reload makes him steady on long payload legs.",
              "Spend your first Hero Token on a hero with splash or a Credit bonus; see the unlock order."]},
    {"id": "Flicker", "role": "Damage", "c": "#ffbe50", "tag": "Time-skipping skirmisher",
     "desc": "Blinks through space and hoses targets with twin rapid-fire pistols. Never stops moving.",
     "stats": {"Difficulty": 3, "Survival": 2, "Mobility": 5, "Damage": 3},
     "passive": ["Light Feet", "+25% movement speed."],
     "weapon": {"name": "Burner SMG", "blurb": "Very fast fire, big magazine, low damage per shot.", "perk": "0.55× damage, 1.9× fire rate. Falls off past 18 studs.",
                "alt": "Aim down sights", "stats": ["0.55× damage", "1.9× fire rate", "40 mag"]},
     "ability": {"name": "Blink", "icon": "Ability_Blink", "cd": 3, "blurb": "Dash 18 studs in the direction you're moving. 3 charges."},
     "ult": {"name": "Time Surge", "icon": "Ult_TimeSurge", "blurb": "For 6s: triple fire rate, bottomless magazine and +40% move speed."},
     "perks": {"minor": [["Fourth Blink", "+1 Blink charge."], ["Hollow Points", "+15% weapon damage."]],
               "major": [["Quantum Reload", "Blinking instantly refills your magazine."], ["Afterimage", "Blinking makes you invulnerable for 1.5s."]]},
     "tips": ["Quantum Reload (Mastery 3) turns every Blink into a free reload.",
              "Great for running between sectors and parkour routes, average for raw Credits.",
              "Stay inside 18 studs: damage falls off to 40% at range."]},
    {"id": "Havoc", "role": "Damage", "c": "#ff3c46", "tag": "Close-range executioner",
     "desc": "A hooded brawler with a scattergun that shreds anything in arm's reach.",
     "stats": {"Difficulty": 2, "Survival": 4, "Mobility": 3, "Damage": 5},
     "passive": ["Soul Siphon", "Heal 25 HP on every kill."],
     "weapon": {"name": "Reaper Scattergun", "blurb": "8 pellets per shot. Brutal up close, useless at range.",
                "perk": "+25% point blank, full damage to 7 studs, 10% by 22 studs.", "alt": "Aim down sights",
                "stats": ["8 pellets", "0.6× fire rate", "8 mag", "Close range"]},
     "ability": {"name": "Wraith Form", "icon": "Ability_Wraith", "cd": 12, "blurb": "Become invulnerable and 50% faster for 2.5s."},
     "ult": {"name": "Death Spiral", "icon": "Ult_DeathSpiral", "blurb": "Spin for 3s, shredding every bot within 14 studs. Take 50% less damage while spinning."},
     "perks": {"minor": [["Tight Choke", "−30% pellet spread."], ["Deep Siphon", "Kills heal 45 HP instead of 25."]],
               "major": [["Lingering Wraith", "Wraith Form lasts 4s and reloads your weapon."], ["Executioner", "Point-blank damage bonus 1.6× instead of 1.25×."]]},
     "tips": ["Walk into the pack: at 22 studs the scattergun does only 10% damage.",
              "Soul Siphon keeps you alive through defender waves on capture points.",
              "Executioner (Mastery 3) is his best perk for farming."]},
    {"id": "Longshot", "role": "Damage", "c": "#dc82ff", "tag": "Precision marksman",
     "desc": "Patient, lethal, and always aiming for the head. Every shot is a big number.",
     "stats": {"Difficulty": 4, "Survival": 2, "Mobility": 2, "Damage": 4},
     "passive": ["Steady Aim", "Crits deal 3× instead of 2×."],
     "weapon": {"name": "Longbow Rail", "blurb": "Slow, pinpoint shots. Crits deal 3×.", "perk": "Up to +50% damage on targets 40+ studs away.",
                "alt": "Scope", "stats": ["1.9× damage", "0.45× fire rate", "6 mag", "1.8s reload"]},
     "ability": {"name": "Deadeye", "icon": "Ability_Deadeye", "cd": 14, "blurb": "Your next 5 hits are guaranteed critical hits."},
     "ult": {"name": "Lockdown", "icon": "Ult_Lockdown", "blurb": "Lock on to every bot in sight (110 studs), then fire: 12× damage to each one."},
     "perks": {"minor": [["Steady Hands", "Deadeye grants 7 guaranteed crits."], ["Bandolier", "+3 magazine size."]],
               "major": [["Marksman", "Long-range bonus up to 2× instead of 1.5×."], ["Headhunter", "+10% critical hit chance."]]},
     "tips": ["Take Bandolier at Mastery 2: the 6-round magazine is his biggest weakness.",
              "Shoot from 40+ studs for the full long-range bonus.",
              "Lockdown is great against a full room of tanky Silver bots."]},
    {"id": "Kestrel", "role": "Damage", "c": "#ffb43c", "tag": "Sky hunter",
     "desc": "A falconer of the high ramparts. Grapples onto anything, fires bolts that burst, and drops out of the sky.",
     "stats": {"Difficulty": 4, "Survival": 2, "Mobility": 5, "Damage": 4},
     "passive": ["Free Runner", "Double jump and wall-run from the start. +20% Momentum from parkour."],
     "weapon": {"name": "Talon Crossbows", "blurb": "Heavy bolts that stick in and burst after a moment, hitting everything nearby.",
                "perk": "Bolts explode after 0.6s for 50% splash (7 studs).", "alt": "Aim down sights",
                "stats": ["1.25× damage", "0.75× fire rate", "12 mag", "Splash"]},
     "ability": {"name": "Grapple Line", "icon": "Ability_Grapple", "cd": 7, "blurb": "Fire a line at any surface you aim at (70 studs) and zip to it."},
     "ult": {"name": "Talon Dive", "icon": "Ult_TalonDive", "blurb": "Leap high into the air, then slam down: 11× damage to every bot within 16 studs of where you land."},
     "perks": {"minor": [["Quick Line", "Grapple Line cooldown −3s."], ["Full Quiver", "+4 magazine size."]],
               "major": [["Cluster Bolts", "Bolt bursts are bigger (10 studs) and hit 70%."], ["Skybreaker", "Talon Dive radius +50% and 30% harder."]]},
     "tips": ["Free Runner gives double jump and wall-run before Silver 4 opens the Mobility tree.",
              "Cluster Bolts makes every shot a small area attack.",
              "The best parkour hero: +20% Momentum on every run."]},
    {"id": "Ember", "role": "Damage", "c": "#ff8228", "tag": "Pyro specialist",
     "desc": "Carries the fire everywhere she goes. Everything she touches keeps burning after she's moved on.",
     "stats": {"Difficulty": 2, "Survival": 3, "Mobility": 3, "Damage": 4},
     "passive": ["Kindling", "Burning bots take +15% damage from you. On Fire heat drains 50% slower."],
     "weapon": {"name": "Cinder Projector", "blurb": "A short-range stream of fire. Bots keep burning after you stop.",
                "perk": "Hits set bots burning for +35% damage over time.", "alt": "",
                "stats": ["4× fire rate", "120 fuel", "24 reach", "Burn"]},
     "ability": {"name": "Firebreak", "icon": "Ability_Firebreak", "cd": 12, "blurb": "Throw down a patch of fire in front of you for 5s. Bots walking through it burn."},
     "ult": {"name": "Inferno", "icon": "Ult_Inferno", "blurb": "Blast a huge cone of fire for 3s: every bot caught takes heavy damage, panics and burns."},
     "perks": {"minor": [["Accelerant", "Burn deals 50% instead of 35%."], ["Big Tank", "+60 fuel (magazine)."]],
               "major": [["Wildfire", "Burning bots that die spread their fire to bots within 10 studs."], ["Scorched Earth", "Firebreak lasts 9s."]]},
     "tips": ["Sweep the stream across a group: burn keeps ticking while you move to the next bot.",
              "Kindling's slower heat drain makes staying On Fire easy.",
              "Wildfire (Mastery 3) chains through a packed Main Hall."]},
    {"id": "Rivet", "role": "Damage", "c": "#50beff", "tag": "Combat engineer",
     "desc": "Builds what the fight needs. Nails that ricochet, a sentry in every pocket, and turrets that never sleep.",
     "stats": {"Difficulty": 2, "Survival": 3, "Mobility": 3, "Damage": 4},
     "passive": ["Salvager", "+30% Scrap. Your built turrets fire 25% faster."],
     "weapon": {"name": "Nail Driver", "blurb": "A rapid nail gun. Every nail ricochets into another bot nearby.",
                "perk": "Hits bounce to a second bot for 40%.", "alt": "Aim down sights", "stats": ["1.05× damage", "0.85× fire rate", "24 mag", "Ricochet"]},
     "ability": {"name": "Pocket Sentry", "icon": "Ability_Sentry", "cd": 18, "blurb": "Drop a mini-turret that shoots the nearest bot for 12s."},
     "ult": {"name": "Overclock Field", "icon": "Ult_OverclockField", "blurb": "For 10s your turrets fire 3× faster, you fire 50% faster, and a free Pocket Sentry drops."},
     "perks": {"minor": [["Hardened Sentry", "Pocket Sentry lasts 20s."], ["Double Ricochet", "Nails bounce to 2 more bots."]],
               "major": [["Twin Sentries", "Pocket Sentry has 2 charges."], ["Overload", "Overclock Field lasts 15s."]]},
     "tips": ["Build turrets in the sector you farm, then pop Overclock Field next to them.",
              "Salvager's extra Scrap pays for the Command tree's Scrap branch.",
              "Double Ricochet (Mastery 2) is excellent in crowded Elite Combat."]},
    {"id": "Broker", "role": "Damage", "c": "#ffcd50", "tag": "War profiteer",
     "desc": "Every bot has a price. Marks the valuable targets, takes a cut of every kill, and turns a fight into a payday.",
     "stats": {"Difficulty": 2, "Survival": 3, "Mobility": 3, "Damage": 3},
     "passive": ["Commission", "+20% Credits from kills and +25% Bounty Marks."],
     "weapon": {"name": "Appraiser", "blurb": "A precise revolver: slow, heavy shots with big crits.", "perk": "Crits deal 2.5×.",
                "alt": "Aim down sights", "stats": ["1.5× damage", "0.55× fire rate", "8 mag", "2.5× crits"]},
     "ability": {"name": "Mark Asset", "icon": "Ability_Mark", "cd": 10, "blurb": "Mark the bot you're facing (90 studs): for 10s it pays 3× Credits and 3× Scrap when it dies."},
     "ult": {"name": "Jackpot", "icon": "Ult_Jackpot", "blurb": "For 8s every kill pays 3× Credits, and you fire 25% faster."},
     "perks": {"minor": [["Retainer", "Marks last 20s."], ["Insider Tip", "+10% critical hit chance."]],
               "major": [["Hostile Takeover", "Mark Asset has 2 charges."], ["Windfall", "Jackpot lasts 12s."]]},
     "tips": ["Mark the WANTED bounty bot: it already pays 10× Credits, and the mark triples that.",
              "Save Jackpot for a fresh wave so every kill in the 8s window counts.",
              "Commission applies to every kill, so he's the best pick on long ranks."]},
    {"id": "Solace", "role": "Support", "c": "#fff0aa", "tag": "Battlefield medic",
     "desc": "A haloed field medic who outlasts everything. Nothing keeps her down for long.",
     "stats": {"Difficulty": 1, "Survival": 4, "Mobility": 3, "Damage": 3},
     "passive": ["Grace", "Regenerate 6 HP per second."],
     "weapon": {"name": "Seraph Caster", "blurb": "Accurate semi-rapid bolts that mend you.", "perk": "Every hit heals you 3 HP.",
                "alt": "Aim down sights", "stats": ["0.95× damage", "1.05× fire rate", "25 mag", "Lifesteal"]},
     "ability": {"name": "Renew", "icon": "Ability_Renew", "cd": 12, "blurb": "Heal 80 HP over 2s and move 30% faster."},
     "ult": {"name": "Sanctuary", "icon": "Ult_Sanctuary", "blurb": "For 10s: you're invulnerable, and you and allies within 30 studs deal 2× damage and earn 2× Credits."},
     "perks": {"minor": [["Abundant Grace", "Regenerate 10 HP per second."], ["Swift Renew", "Renew cooldown −4s."]],
               "major": [["Vampiric Bolts", "Hits heal 7 HP instead of 3."], ["Eternal Sanctuary", "Sanctuary lasts 15s."]]},
     "tips": ["Eternal Sanctuary (Mastery 3) stretches the best burst in the game to 15s.",
              "Regeneration lets her hold capture points solo through defender waves.",
              "In a group, stand in the middle when you cast: everyone within 30 studs gets 2× Credits."]},
    {"id": "Vesper", "role": "Support", "c": "#be78ff", "tag": "Bio-alchemist",
     "desc": "A rogue alchemist who drinks the fight. Her siphon drains bots to keep her alive, and her orbs keep the squad going.",
     "stats": {"Difficulty": 3, "Survival": 4, "Mobility": 3, "Damage": 3},
     "passive": ["Symbiosis", "Your Squad Bonus is doubled: +20% Credits per friend in your server."],
     "weapon": {"name": "Siphon Gauntlet", "blurb": "A short-range draining stream that locks on easily and heals you as it hits.",
                "perk": "Never reloads. Every hit heals you 1.2 HP.", "alt": "Aim down sights", "stats": ["5× fire rate", "26 reach", "No reload", "Lifesteal"]},
     "ability": {"name": "Bloom Orb", "icon": "Ability_Bloom", "cd": 10, "blurb": "Throw an orb that bounces around for 6s, draining bots it passes and healing you and allies nearby."},
     "ult": {"name": "Confluence", "icon": "Ult_Confluence", "blurb": "For 7s project a 50-stud siphon beam that pierces every bot in a line and heals you as it drains. Move 30% faster."},
     "perks": {"minor": [["Potency", "Siphon heals 50% more."], ["Swift Bloom", "Bloom Orb cooldown −3s."]],
               "major": [["Overgrowth", "Bloom Orb lasts 10s and reaches further."], ["Deep Confluence", "Confluence lasts 10s."]]},
     "tips": ["Symbiosis only counts friends in your server: with 3 friends it's +60% Credits.",
              "Confluence pierces, so line it up along a payload track.",
              "Solo, she's a steady B-tier farmer that never stops to reload."]},
]

# --------------------------------------------------------------------------------------------- tier list + unlock order (owner's picks)
TIERS = [
    {"t": "S", "c": "#ff4a5a", "heroes": [
        ["Broker", "+20% Credits on every kill, Jackpot makes kills pay 3×, and marked bots pay 3×."],
        ["Bulwark", "Cleaves whole packs, ignores armor and can sit on objectives."],
        ["Solace", "Sanctuary gives 2× damage and 2× Credits for 10 seconds."]]},
    {"t": "A", "c": "#f99e1a", "heroes": [
        ["Kestrel", "Bolts burst for splash damage on every hit."],
        ["Rivet", "Ricochet damage, and better than ever now that turrets open at Bronze 3."],
        ["Anchor", "Tether and Undertow pull bots into tight groups."],
        ["Havoc", "Hits very hard up close and heals 25 HP on every kill."]]},
    {"t": "B", "c": "#ffcf5a", "heroes": [
        ["Vanguard", "Solid at every range, but nothing extra."],
        ["Ember", "Solid but nothing extra. Her burn shines early in the crowded Main Hall."],
        ["Flicker", "Solid but nothing extra. Fast and fun to play."],
        ["Vesper", "Her passive only helps with friends in the server. In a group she's S tier."]]},
    {"t": "C", "c": "#5ac8ff", "heroes": [
        ["Longshot", "A 6-round magazine and a slow reload cost too much time between kills."]]},
]

# every rank up (and the promotion) pays one Hero Token; Vanguard is free
UNLOCK_ORDER = [
    ["Bronze 5", "Ember", "Best-feeling weapon early: 4× fire rate, a 120-round magazine, and burn keeps killing while you swap targets. The crowded Main Hall suits her short range."],
    ["Bronze 4", "Bulwark", "The payload unlocks now. He cleaves whole squads, has 250 HP and can stand on the cart. Armor pierce pays off again at Bronze 3 against Armored bots."],
    ["Bronze 3", "Broker", "Bounties open now (+25% Marks). Just before the long ranks, +20% on every kill, 3× Mark Asset and the Jackpot ult start to matter. His slow revolver is the trade-off."],
    ["Bronze 2", "Solace", "Capture points open, and she can hold them because she regenerates. Sanctuary gives 2× damage and 2× Credits for 10 seconds, the best burst of income in a 30–70 minute rank."],
    ["Bronze 1", "Rivet", "Turrets have been open since Bronze 3, and his +30% Scrap and faster turrets feed the Command tree's Scrap branch. Bounce hits are good in Elite Combat."],
    ["Promotion", "Anchor", "Heavy Hauler makes the Silver siege robot roll 50% faster, and Silver 5 is when the Push opens."],
    ["Silver 5 / 4", "Kestrel", "Free double jump and wall-run, plus +20% Momentum for the Silver 4 parkour. Splash damage handles Sturmfeste packs."],
    ["Next", "Havoc", "A strong brawler, but you need to be in close."],
    ["Next", "Flicker", "Feels great (1.9× fire rate, +25% speed), but is only average for speed."],
    ["Next", "Vesper", "5× fire rate and never reloads. Her Squad Bonus doubles only with friends, so buy her earlier if you play in a group."],
    ["Last", "Longshot", "A 6-round magazine and a slow reload lose too much time."],
]

# --------------------------------------------------------------------------------------------- codes
CODES = [
    {"code": "LAUNCH", "reward": "+50 Cargo and 20 minutes of 2× Credits", "req": "Anyone"},
    {"code": "STURMFESTE", "reward": "+40 Crowns and 15 minutes of 2× Credits", "req": "Silver (after your first promotion)"},
    {"code": "THANKYOU", "reward": "+1 Hero Token", "req": "Anyone", "expires": "2026-12-31"},
]

KEYS = [["Q", "Ultimate"], ["E", "Ability / interact"], ["RMB", "Aim, scope or guard"], ["F", "Upgrades"], ["X", "Shop"], ["H", "Heroes"],
        ["C", "Cargo Bay"], ["N", "Command tree"], ["Y", "Runes"], ["T", "Fast travel"], ["V", "Menu"], ["J", "Profile"],
        ["P", "Season Pass"], ["B", "Weekly boards"], ["M", "Mobility tree"], ["L", "Research Lab"], ["K", "Trials"], ["G", "Grapple"],
        ["Ctrl", "Dash"], ["Alt", "Free the cursor"]]

# --------------------------------------------------------------------------------------------- ranks
RANKS = [
    {"name": "Unranked", "cost": 0, "mult": 1, "a": "#5a606a", "b": "#bec6d0"},
    {"name": "Bronze 5", "cost": 5e3, "mult": 3, "a": "#6e3e20", "b": "#e09e5c"},
    {"name": "Bronze 4", "cost": 45e3, "mult": 5, "a": "#6e3e20", "b": "#e09e5c"},
    {"name": "Bronze 3", "cost": 540e3, "mult": 9, "a": "#6e3e20", "b": "#e09e5c"},
    {"name": "Bronze 2", "cost": 75e6, "mult": 14, "a": "#6e3e20", "b": "#e09e5c"},
    {"name": "Bronze 1", "cost": 37e9, "mult": 20, "a": "#6e3e20", "b": "#e09e5c"},
    {"name": "Silver 5", "cost": 130e12, "mult": 40, "a": "#8c919b", "b": "#ebf0f5"},
    {"name": "Silver 4", "cost": 6.7e21, "mult": 60, "a": "#8c919b", "b": "#ebf0f5"},
    {"name": "Silver 3", "cost": 9.6e22, "mult": 90, "a": "#8c919b", "b": "#ebf0f5"},
    {"name": "Silver 2", "cost": 2e23, "mult": 135, "a": "#8c919b", "b": "#ebf0f5"},
    {"name": "Silver 1", "cost": 1.7e24, "mult": 200, "a": "#8c919b", "b": "#ebf0f5"},
]
# rough playtime to reach each rank for an active player (the game's pacing target, fast start / slow finish)
RANK_TIME = {1: "~3 min", 2: "~6 min", 3: "~12 min", 4: "~30 min", 5: "~70 min", 6: "~2 h", 7: "~3 h", 8: "~4.5 h", 9: "~6 h", 10: "~6.5 h"}
REDEPLOY_MIN = [4000, 8000, 15000, 25000, 40000, 60000, 80000, 110000, 150000, 200000]

SYSTEMS = {
    "OnFire": {"t": "On Fire", "icon": "OnFire", "b": "Chain kills without getting hit to build heat: up to 2.5× kill Credits.", "page": "objectives/#on-fire"},
    "Ultimate": {"t": "Ultimates", "icon": "Ultimate", "b": "Damage and kills charge your hero's ultimate. Press Q when it's ready.", "page": "heroes/"},
    "Redeploy": {"t": "Redeploy", "icon": "Redeploy", "b": "Cash in Credits for Redeploy points and Rank XP; spend RP on the Redeploy tree.", "page": "currencies/#redeploy"},
    "HeroSelect": {"t": "Hero Tokens", "icon": "HeroToken", "b": "Every rank up pays a Hero Token: unlock any hero at the Hero terminal (H).", "page": "tier-list/#unlock-order"},
    "Payload": {"t": "Payload", "icon": "Payload", "b": "Three carts, one per sector. Escort them for Cargo, Credits and Rank XP.", "page": "objectives/#payload"},
    "CargoBay": {"t": "Cargo Bay", "icon": "Cargo", "b": "Permanent upgrades bought with Cargo (C). Never resets.", "page": "upgrades/#cargo"},
    "Mastery": {"t": "Hero Mastery", "icon": "Mastery", "b": "Kills level your hero: a minor perk at Mastery 2, a major perk at 3.", "page": "objectives/#mastery"},
    "Turrets": {"t": "Scrap & Turrets", "icon": "Turrets", "b": "Bots drop Scrap. Build turrets at the glowing sockets.", "page": "objectives/#turrets"},
    "Bounties": {"t": "Bounties", "icon": "Marks", "b": "A WANTED bot appears every 2.5 minutes. Kill it for Bounty Marks.", "page": "objectives/#bounties"},
    "AdvancedCombat": {"t": "Advanced Combat", "icon": "Travel", "b": "Buy the gate for 1M Credits: Armored bots pay 10× Training bots.", "page": "bots/"},
    "Runes": {"t": "Runes", "icon": "Runes", "b": "Free rune altars in the Armory: stand on one to roll permanent bonuses.", "page": "runes/"},
    "Control": {"t": "Capture Points", "icon": "CP", "b": "Three points (A, B, C). A full capture pays Competitive Points.", "page": "objectives/#control"},
    "CommandTree": {"t": "Command Tree", "icon": "Command", "b": "Spend CP (and Scrap) on the Command tree (N).", "page": "upgrades/#command"},
    "EliteCombat": {"t": "Elite Combat", "icon": "Travel", "b": "Buy the gate for 5B Credits: Elite bots pay the most in the Facility.", "page": "bots/"},
    "Promotion": {"t": "Tier Promotion", "icon": "Promotion", "b": "Promote to Silver: trade this tier's Redeploy progress for Skill Rating.", "page": "ranks/#promotion"},
    "Dropship": {"t": "The Dropship", "icon": "Island", "b": "The Armory's back door opens onto the dropship to Sturmfeste.", "page": "sturmfeste/"},
    "Sturmfeste": {"t": "Sturmfeste", "icon": "Sturmfeste", "b": "A storm-lashed castle town whose bots pay far more than the Facility's.", "page": "sturmfeste/"},
    "Push": {"t": "Siege Push", "icon": "Crowns", "b": "Escort the siege robot to the throne. Checkpoints pay Crowns.", "page": "sturmfeste/#push"},
    "TempestRune": {"t": "Rune of the Tempest", "icon": "Runes", "b": "A new altar in the Rune Sanctum next to the tavern.", "page": "runes/#tempest"},
    "WorldBoss": {"t": "World Boss", "icon": "WorldBoss", "b": "The Storm Colossus rises on the Stormfield every hour.", "page": "events/#world-boss"},
    "Mobility": {"t": "Mobility", "icon": "Momentum", "b": "Parkour pays Momentum for double jump, dash, wall-run and grapple.", "page": "sturmfeste/#parkour"},
    "Research": {"t": "Research Lab", "icon": "Research", "b": "Spend Crowns on timed research that keeps running while you're offline.", "page": "sturmfeste/#research"},
    "Trials": {"t": "Trials", "icon": "Trials", "b": "Challenge runs with a handicap for permanent rewards and automation.", "page": "sturmfeste/#trials"},
    "HonorHall": {"t": "Honor Hall", "icon": "Honor", "b": "Honor from Trials and Wardens speeds up the Research Lab.", "page": "upgrades/#honor"},
    "TempestForge": {"t": "Tempest Forge", "icon": "StormEssence", "b": "Storm Essence from the World Boss lifts every Silver currency.", "page": "upgrades/#forge"},
}
UNLOCKS = {0: ["OnFire", "Ultimate"], 1: ["Redeploy", "HeroSelect"], 2: ["Payload", "CargoBay"], 3: ["Mastery", "Turrets", "Bounties", "AdvancedCombat"],
           4: ["Runes", "Control", "CommandTree"], 5: ["EliteCombat", "Promotion"], 6: ["Dropship", "Sturmfeste", "Push", "TempestRune", "WorldBoss"],
           7: ["Mobility"], 8: ["Research"], 9: ["Trials", "HonorHall"], 10: ["TempestForge"]}

# --------------------------------------------------------------------------------------------- currencies
# resets: "run" = Redeploy and rank up, "rank" = rank up only, "never"
CURRENCIES = [
    {"id": "credits", "name": "Credits", "icon": "Credits", "unlock": "Start", "resets": "run",
     "earn": "Every bot kill: base payout × your rank's Credit multiplier × every upgrade, rune and boost.",
     "spend": "Credit upgrades (F), rank ups, the Advanced (1M) and Elite (5B) Combat gates, and rune rolls.",
     "note": "Cashed in by Redeploy, and reset when you rank up."},
    {"id": "redeploy", "name": "Redeploy points (RP)", "icon": "Redeploy", "unlock": "Bronze 5", "resets": "rank",
     "earn": "Redeploy on the Redeploy board: RP = √(Credits ÷ 150) × 2^Redeploy Multiplier × Fast Track × boosts. You need a minimum of 4K Credits at Bronze 5, up to 200K at Silver 1.",
     "spend": "The Redeploy tab: Redeploy Multiplier, Credit Surge, Combat Pay, Combat Power, Quartermaster, Head Start and rune upgrades.",
     "note": "Kept through Redeploys, reset on rank up. Standing Orders (Cargo Bay) keeps some nodes."},
    {"id": "cargo", "name": "Cargo", "icon": "Cargo", "unlock": "Bronze 4", "resets": "never",
     "earn": "Payload checkpoints and deliveries, +2 per Redeploy (more with Salvage Crates) and 20 × your new rank on every rank up.",
     "spend": "The Cargo Bay (C): permanent Credit, damage, Redeploy and automation upgrades.", "note": "Never resets."},
    {"id": "scrap", "name": "Scrap", "icon": "Scrap", "unlock": "Bronze 3", "resets": "rank",
     "earn": "Bots drop Scrap 45% of the time: Bronze (×1), Silver (×2.5) or Gold (×6) pieces. Walk over it, or max Scrap Magnet to auto-collect.",
     "spend": "Turrets at the glowing sockets, and the Scrap branch of the Command tree.", "note": "Resets on rank up."},
    {"id": "marks", "name": "Bounty Marks", "icon": "Marks", "unlock": "Bronze 3", "resets": "never",
     "earn": "WANTED bounty bots: 4 (Training) to 28 (Warden) Marks. Broker gets +25%.",
     "spend": "The Bounty tab: Skin Vouchers, Ticket Bundles, Mastery Tomes, Bounty Scope and Trophy Hunter.", "note": "Never resets."},
    {"id": "cp", "name": "Competitive Points (CP)", "icon": "CP", "unlock": "Bronze 2", "resets": "never",
     "earn": "Completing a capture: 10 CP at Point A, ×5 at B and ×25 at C (plus upgrades).",
     "spend": "The Command tree (N): rune stats, capture speed, cheaper rune rolls, Scrap Magnet.", "note": "Never resets."},
    {"id": "sr", "name": "Skill Rating (SR)", "icon": "SR", "unlock": "Promotion", "resets": "never",
     "earn": "Tier Promotion: SR = √(Redeploy points earned this tier ÷ 2), rounded down.",
     "spend": "The Skill Rating tab: permanent Credits, damage, Redeploy, Logistics and Auto-Capture.", "note": "Never resets."},
    {"id": "crowns", "name": "Crowns", "icon": "Crowns", "unlock": "Silver 5", "resets": "never",
     "earn": "Siege Push checkpoints (20 / 45 / 80 / 150), day 5 of the daily streak in Silver, and the Crown Pouch.",
     "spend": "Research Lab projects.", "note": "Never resets."},
    {"id": "momentum", "name": "Momentum", "icon": "Momentum", "unlock": "Silver 4", "resets": "never",
     "earn": "Parkour courses (25 / 50 / 90 per run), 3× on a first clear, +50% on a new best.",
     "spend": "The Mobility tree (M): double jump, dash, wall-run, grapple and siege upgrades.", "note": "Never resets."},
    {"id": "honor", "name": "Honor", "icon": "Honor", "unlock": "Silver 2", "resets": "never",
     "earn": "Trial clears (10 per tier) and Warden kills.", "spend": "The Honor Hall: faster research, more Crowns, a third workbench, Lab Steward.", "note": "Never resets."},
    {"id": "essence", "name": "Storm Essence", "icon": "StormEssence", "unlock": "Silver 1", "resets": "never",
     "earn": "World Boss fights and full siege runs.", "spend": "The Tempest Forge: more Crowns, Momentum and Honor, and damage.", "note": "Never resets."},
    {"id": "tickets", "name": "Tickets", "icon": "Ticket", "unlock": "Start", "resets": "never",
     "earn": "1 every 5 minutes in game (never offline), World Boss (15), weekly boards (40–500), the Season Pass, Ticket Bundles and new rune tiers.",
     "spend": "Shop boosts, potion packs (20 for 10 potions) and skins (600 each).", "note": "Never resets."},
    {"id": "tokens", "name": "Hero Tokens", "icon": "HeroToken", "unlock": "Bronze 5", "resets": "never",
     "earn": "Every rank up, the promotion, the THANKYOU code, the Starter Pack or the Store.",
     "spend": "Unlock any hero at the Hero terminal (H).", "note": "Only rank ups and the Store give Hero Tokens."},
    {"id": "skintokens", "name": "Skin Tokens", "icon": "SkinToken", "unlock": "Start", "resets": "never",
     "earn": "Day 7 of the daily streak, Skin Vouchers (Bounty tab), Season Pass tiers or the Store.",
     "spend": "Any hero skin of your choice.", "note": "Skins are cosmetic only."},
]
MILESTONES = "The first time you earn 10, 100 and 1,000 of a new currency (Redeploy, Cargo, CP, SR, Crowns, Momentum, Honor, Storm Essence) you get a free upgrade node for it and ×3 of that currency for 10 minutes."

# --------------------------------------------------------------------------------------------- upgrade trees
# node: [title, blurb, per-level effect, max-level effect, max, base cost, growth (×mult for exponential, +n for linear), rank or ""]
TREES = [
    {"id": "credit", "title": "Credit upgrades", "tab": "CREDIT (F)", "wallet": "Credits", "icon": "Credits", "curve": "exp", "unlock": "Start",
     "resets": "On Redeploy and rank up.",
     "blurb": "Your core power. Prices scale with your rank multiplier and Combat Pay, so they stay a similar share of your income. The Quartermaster (Redeploy tab) can buy these for you.",
     "nodes": [
         ["Damage", "Hit harder with every shot", "+10 dmg", "+1,000 dmg", 100, 10, 1.92, ""],
         ["Fire Rate", "Shoot faster", "+10% speed", "+200% speed", 20, 27, 1.83, ""],
         ["Credit Multiplier", "Multiplies Credits per kill", "×2 Credits", "×101 Credits", 100, 120, 1.5, ""],
         ["Crit Chance", "Chance to deal double damage", "10% crit", "30% crit", 5, 300, 1.9, "Bronze 4"],
         ["Rune Speed", "Roll runes faster at every altar", "+20% rolls", "+300% rolls", 15, 500, 5.5, "Bronze 2"],
         ["Rune Luck", "Rarer rune tiers come up more often", "+25% luck", "+375% luck", 15, 800, 6, "Bronze 2"],
         ["Rune Bulk", "More runes from every roll", "+30% runes", "+360% runes", 12, 2000, 7, "Bronze 2"]]},
    {"id": "redeploy", "title": "Redeploy tree", "tab": "REDEPLOY (F)", "wallet": "RP", "icon": "Redeploy", "curve": "mixed", "unlock": "Bronze 5",
     "resets": "On rank up (Standing Orders keeps some nodes).",
     "blurb": "The first prestige layer. Redeploy Multiplier and Credit Surge double your gains per level; buy them first every rank.",
     "nodes": [
         ["Redeploy Multiplier", "Doubles every Redeploy payout, per level", "×2 payout", "×4,096 payout", 12, 5, "×5", ""],
         ["Credit Surge", "Doubles every kill's Credits, per level (upgrade prices don't rise)", "×2 Credits", "×32,768 Credits", 15, 8, "×8", ""],
         ["Combat Power", "Damage boost until your next rank up", "+25% dmg", "+2,500% dmg", 100, 2, "+3", ""],
         ["Combat Pay", "+100% kill Credits per level (Credit upgrade prices scale too)", "×2 Credits", "×101 Credits", 100, 3, "+4", ""],
         ["Quartermaster", "Auto-buys the cheapest Credit upgrade every 2 s (toggle on its card)", "Online", "Online", 1, 3, "", ""],
         ["Head Start", "Start every Redeploy run with free Damage + Fire Rate levels", "+2 levels", "+20 levels", 10, 4, "+4", ""],
         ["Rapid Deployment", "Permanent fire rate boost for this rank", "+5% speed", "+200% speed", 40, 5, "+6", "Bronze 4"],
         ["Elite Hunter", "Bonus damage vs Elite bots", "+25% vs Elite", "+1,250% vs Elite", 50, 50, "+25", "Bronze 1"],
         ["Rune Speed", "Roll runes faster at every altar", "+20% rolls", "+300% rolls", 15, 10, "×4", "Bronze 2"],
         ["Rune Luck", "Rarer rune tiers come up more often", "+25% luck", "+375% luck", 15, 15, "×4.5", "Bronze 2"],
         ["Rune Bulk", "More runes from every roll", "+30% runes", "+360% runes", 12, 30, "×5", "Bronze 2"]]},
    {"id": "cargo", "title": "Cargo Bay", "tab": "CARGO BAY (C)", "wallet": "Cargo", "icon": "Cargo", "curve": "exp", "unlock": "Bronze 4",
     "resets": "Never.",
     "blurb": "A hex tree of permanent upgrades. Each node needs its parent first. Start with Supply Drop and Armory Uplink, then Priority Shipping for more Cargo.",
     "nodes": [
         ["Supply Drop", "More Credits from everything", "+10% Credits", "+300% Credits", 30, 20, 1.45, ""],
         ["Logistics Network", "Bigger Redeploy payouts", "+10% payout", "+300% payout", 30, 30, 1.5, ""],
         ["Priority Shipping", "More Cargo from every source", "+25% Cargo", "+500% Cargo", 20, 25, 1.55, ""],
         ["Salvage Crates", "Extra Cargo every time you Redeploy", "+2 Cargo", "+30 Cargo", 15, 30, 1.6, ""],
         ["Convoy Bonus", "Bigger Cargo bonus when you rank up", "+50%", "+500%", 10, 40, 1.7, ""],
         ["Escort Pay", "Bigger Payload rewards", "+15%", "+150%", 10, 60, 1.8, "Bronze 4"],
         ["Rune Attunement", "Better odds on every rune altar", "+25% rune Luck", "+75% rune Luck", 3, 150, 4, "Bronze 2"],
         ["Armory Uplink", "More damage for every hero", "+10% dmg", "+300% dmg", 30, 20, 1.45, ""],
         ["Rapid Cycler", "Every weapon fires faster", "+4% fire rate", "+40% fire rate", 10, 35, 1.6, ""],
         ["Targeting Suite", "More critical hits", "+1% crit", "+10% crit", 10, 50, 1.65, ""],
         ["Heavy Munitions", "Multiplies ALL damage", "×1.25 dmg", "×3.05 dmg", 5, 300, 2.5, ""],
         ["Reinforced Hull", "Take less damage", "−3% damage taken", "−30% damage taken", 10, 40, 1.6, ""],
         ["Fuel Line", "On Fire heat drains slower", "−8% drain", "−80% drain", 10, 30, 1.7, ""],
         ["Ult Capacitor", "Ultimates charge faster", "+8% charge", "+120% charge", 15, 40, 1.7, ""],
         ["Overclock", "Ultimates charge faster", "+10% charge", "+100% charge", 10, 45, 1.6, ""],
         ["Afterburners", "Move faster with every hero", "+2% speed", "+20% speed", 10, 35, 1.55, ""],
         ["Quartermaster Cache", "Multiplies ALL Credits", "×1.25 Credits", "×3.05 Credits", 5, 300, 2.5, ""],
         ["Salvage Rig", "More Scrap from every kill", "+20% Scrap", "+400% Scrap", 20, 20, 1.6, "Bronze 2"],
         ["Turret Calibration", "Your turrets hit harder", "+10% turret dmg", "+250% turret dmg", 25, 50, 1.65, "Bronze 2"],
         ["Auto-Redeploy", "Redeploys for you once the payout stops growing (toggle on the node)", "Online", "Online", 1, 60, "", ""],
         ["Redeploy Quartermaster", "Auto-buys the cheapest Redeploy upgrade (toggle on the node)", "Online", "Online", 1, 150, "", ""],
         ["Standing Orders", "Keep Redeploy nodes through rank up: Quartermaster + Head Start, then Credit Surge, then Redeploy Multiplier", "Level 1", "Level 3", 3, 250, 3, ""]]},
    {"id": "bounty", "title": "Bounty shop", "tab": "BOUNTY (F)", "wallet": "Marks", "icon": "Marks", "curve": "lin", "unlock": "Bronze 3",
     "resets": "Never.", "blurb": "Bounty Marks buy items and permanent bonuses. Each purchase costs a little more than the last.",
     "nodes": [
         ["Skin Voucher", "+1 Skin Token: unlock any hero skin", "1 token", "40 tokens", 40, 60, "+30", ""],
         ["Ticket Bundle", "+20 Tickets for the Shop", "20 tickets", "4,000 tickets", 200, 15, "+3", ""],
         ["Mastery Tome", "+250 Mastery XP for the hero you're playing", "+250 XP", "200 tomes", 200, 6, "+2", ""],
         ["Bounty Scope", "More Marks from every bounty", "+20% Marks", "+200% Marks", 10, 10, "+6", ""],
         ["Trophy Hunter", "More Credits from everything", "+15% Credits", "+300% Credits", 20, 25, "+15", ""]]},
    {"id": "command", "title": "Command tree", "tab": "COMMAND (N)", "wallet": "CP / Scrap", "icon": "Command", "curve": "exp", "unlock": "Bronze 2",
     "resets": "Never.", "blurb": "Bought with CP from capture points. Once you've built a turret, the Scrap branch opens and takes Scrap instead.",
     "nodes": [
         ["Field Command", "Boosts rune Speed, Luck and Bulk", "+15% rune stats", "+375% rune stats", 25, 10, 1.55, ""],
         ["Capture Drive", "More CP from every capture", "+10% CP", "+100% CP", 10, 30, 1.7, ""],
         ["Fortified Points", "Capture points fill faster while you hold them", "+10% speed", "+80% speed", 8, 45, 1.75, ""],
         ["Rune Rations", "Rune rolls cost fewer Credits", "−8% price", "−49% price", 8, 25, 1.8, ""],
         ["Scrap Magnet", "Bigger Scrap pickup radius; max level collects everything", "+6 studs", "Auto-collect", 5, 15, 1.7, ""],
         ["Salvage Crews (Scrap)", "Your turrets hit harder", "+15% turret dmg", "+225% turret dmg", 15, 40, 1.6, "Build a turret"],
         ["Rune Engine (Scrap)", "Your last altar keeps rolling wherever you are", "10% speed", "50% speed", 5, 150, 2.2, "Build a turret"],
         ["Engineers (Scrap)", "Lv1 auto-upgrades your turrets; Lv2 keeps them through rank up", "Auto-upgrade", "Auto-upgrade + keep", 2, 300, 4, "Build a turret"]]},
    {"id": "sr", "title": "Skill Rating", "tab": "SKILL RATING (F)", "wallet": "SR", "icon": "SR", "curve": "lin", "unlock": "Promotion",
     "resets": "Never.", "blurb": "Paid for with SR from Tier Promotion. Every node is permanent.",
     "nodes": [
         ["Veteran's Pay", "Permanent Credit boost", "+25% Credits", "+1,250% Credits", 50, 1, "+1", ""],
         ["Iron Sights", "Permanent damage boost", "+10% dmg", "+500% dmg", 50, 1, "+1", ""],
         ["Fast Track", "Permanent Redeploy payout boost", "+10% payout", "+250% payout", 25, 2, "+2", ""],
         ["Overclock", "Ultimates charge faster", "+10% charge", "+100% charge", 10, 2, "+2", ""],
         ["Hot Hands", "On Fire tiers pay more", "+10% heat bonus", "+100% heat bonus", 10, 2, "+2", ""],
         ["Logistics", "More Cargo, CP and Scrap", "+25%", "+625%", 25, 2, "+2", ""],
         ["Auto-Capture", "Open capture points capture themselves at 25% speed while nobody holds them", "Online", "Online", 1, 5, "", ""]]},
    {"id": "mobility", "title": "Mobility tree", "tab": "MOBILITY (M)", "wallet": "Momentum", "icon": "Momentum", "curve": "exp", "unlock": "Silver 4",
     "resets": "Never.", "blurb": "Movement tech and siege upgrades bought with Momentum from parkour runs.",
     "nodes": [
         ["Stride", "Move faster everywhere", "+4% speed", "+40% speed", 10, 15, 1.35, ""],
         ["Spring Greaves", "Jump higher", "+10% jump", "+50% jump", 5, 25, 1.5, ""],
         ["Double Jump", "Press jump again in mid-air", "Double jump", "Double jump", 1, 120, "", ""],
         ["Triple Jump", "A third jump in mid-air", "Triple jump", "Triple jump", 1, 900, "", ""],
         ["Dash", "Burst forward (Ctrl)", "Dash", "Dash", 1, 80, "", ""],
         ["Quick Recovery", "Dash more often", "−12% cooldown", "−60% cooldown", 5, 60, 1.6, ""],
         ["Long Stride", "Dash further", "+15% distance", "+75% distance", 5, 60, 1.6, ""],
         ["Wall Run", "Jump into a wall while moving to run along it", "Wall run", "Wall run", 1, 200, "", ""],
         ["Wall Stamina", "Run along walls for longer", "1.6s", "3.2s", 5, 80, 1.6, ""],
         ["Grapple Hook", "Swing to iron grapple rings (G)", "Grapple", "Grapple", 1, 450, "", ""],
         ["Long Line", "Grapple from further away", "+20% range", "+100% range", 5, 120, 1.6, ""],
         ["Flow State", "More Momentum from parkour runs", "+10%", "+100%", 10, 30, 1.45, ""],
         ["Courier Pay", "Parkour runs also pay Credits", "+10 kills' worth", "+50 kills' worth", 5, 150, 2, ""],
         ["Siege Drive", "The siege robot rolls faster while you escort it", "+10%", "+100%", 10, 40, 1.55, ""],
         ["Crown Press", "More Crowns from every siege checkpoint", "+10%", "+150%", 15, 60, 1.6, ""],
         ["Steam Winch", "The siege robot winches itself forward while you're on the island (you earn the Crowns)", "20% speed", "20% speed", 1, 800, "", ""]]},
    {"id": "honor", "title": "Honor Hall", "tab": "HONOR HALL (F)", "wallet": "Honor", "icon": "Honor", "curve": "exp", "unlock": "Silver 2",
     "resets": "Never.", "blurb": "Honor from Trials and Wardens speeds up and automates the Research Lab.",
     "nodes": [
         ["Research Haste", "Every Lab project finishes faster", "−8% time", "−57% time", 10, 5, 1.6, ""],
         ["Crown Tithe", "More Crowns from the siege", "+10%", "+200%", 20, 8, 1.5, ""],
         ["Third Workbench", "Research one more project at once", "+1 bench", "+1 bench", 1, 60, "", ""],
         ["Lab Steward", "Free workbenches start the cheapest project you can afford", "Online", "Online", 1, 40, "", ""]]},
    {"id": "forge", "title": "Tempest Forge", "tab": "TEMPEST FORGE (F)", "wallet": "Storm Essence", "icon": "StormEssence", "curve": "exp", "unlock": "Silver 1",
     "resets": "Never.", "blurb": "Storm Essence from the World Boss and full siege runs lifts every Silver currency.",
     "nodes": [
         ["Storm Heart", "More Crowns, Momentum and Honor", "+15%", "+300%", 20, 3, 1.6, ""],
         ["Honor Guard", "More Honor from Trials and Wardens", "+15%", "+150%", 10, 5, 1.7, ""],
         ["Tempest Edge", "Permanent damage", "+10% dmg", "+100% dmg", 10, 8, 1.8, ""]]},
]

# --------------------------------------------------------------------------------------------- runes
RUNE_STATS = {
    "Credits": ["Credits", "#5ac8ff"], "Damage": ["Damage", "#ff6e5a"], "Redeploy": ["Redeploy", "#ffb741"], "Cargo": ["Cargo", "#78e696"],
    "Salvage": ["Scrap", "#5ae6e6"], "Crowns": ["Crowns", "#ffcd50"], "Momentum": ["Momentum", "#6ee6f0"], "PayloadSpeed": ["Payload speed", "#78e696"],
    "RuneLuck": ["Luck", "#6ee678"], "RuneBulk": ["Bulk", "#5aaaff"], "RuneSpeed": ["Speed", "#ffc846"],
}
# tier: [name, odds (1 in N) or weight %, bonus at [MAX], count for [MAX], milestone]
ALTARS = [
    {"id": "Fortune", "name": "Rune of Fortune", "color": "#ffc446", "where": "Armory (behind the Training Hub)", "unlock": "Bronze 2", "rank": 4,
     "focus": "Credits, Redeploy, Cargo and payload speed. Your first altar: max it before Bronze 1.",
     "tiers": [["Copper", 1, {"Credits": 2}, 5000, ""], ["Silver", 5, {"Redeploy": 1.5, "Cargo": 1.5, "RuneBulk": 1.2}, 2000, ""],
               ["Gilded", 30, {"PayloadSpeed": 1.25, "Credits": 2.5}, 1000, ""], ["Jewel", 200, {"Redeploy": 2, "RuneSpeed": 1.25, "Cargo": 2}, 300, ""],
               ["Royal", 1500, {"PayloadSpeed": 1.5, "Credits": 3}, 250, "Payloads creep forward on their own at 25% speed."],
               ["Treasure", 20000, {"RuneLuck": 1.5, "Credits": 3}, 100, "Payloads escort themselves at 50% speed while you're away."],
               ["Hoard", 300000, {"Redeploy": 5, "Cargo": 3, "RuneBulk": 2}, 40, ""], ["Midas", 5000000, {"Redeploy": 3, "Cargo": 4, "Credits": 4}, 15, ""]]},
    {"id": "Valor", "name": "Rune of Valor", "color": "#aa6eff", "where": "Armory (behind the Training Hub)", "unlock": "Bronze 1", "rank": 5,
     "focus": "Damage and Credits. It maxes out around Silver 4–3.",
     "tiers": [["Spark", 1, {"Damage": 2}, 10000, ""], ["Glimmer", 4, {"RuneLuck": 1.2, "Credits": 2}, 5000, ""], ["Pulse", 25, {"RuneSpeed": 1.3, "Damage": 2.5}, 2000, ""],
               ["Surge", 150, {"Redeploy": 1.5, "Credits": 2.5}, 500, ""], ["Overdrive", 1000, {"RuneLuck": 1.5, "Damage": 3}, 300, ""],
               ["Apex", 10000, {"Redeploy": 2, "Credits": 3}, 120, ""], ["Mythic", 150000, {"RuneBulk": 2, "Damage": 3}, 40, ""],
               ["Transcendent", 3000000, {"Damage": 3, "Credits": 3}, 15, ""]]},
    {"id": "Tempest", "name": "Rune of the Tempest", "color": "#5ac8ff", "where": "Rune Sanctum (next to the Sturmhorn Tavern)", "unlock": "Silver 5", "rank": 6,
     "focus": "Crowns, Momentum and damage for the Silver systems.",
     "tiers": [["Drizzle", 1, {"Crowns": 1.25}, 10000, ""], ["Gale", 6, {"Momentum": 1.25}, 4000, ""], ["Thunder", 40, {"Crowns": 1.5, "RuneSpeed": 1.25}, 1500, ""],
               ["Cyclone", 300, {"Momentum": 1.5, "Damage": 1.5}, 400, ""], ["Maelstrom", 2500, {"Crowns": 2, "RuneLuck": 1.5}, 100, ""],
               ["Stormeye", 40000, {"Damage": 2, "Credits": 2}, 25, ""], ["Stormborn", 600000, {"Crowns": 3, "RuneBulk": 2}, 5, ""],
               ["Tempest King", 10000000, {"Crowns": 5, "Credits": 5}, 2, ""]]},
    {"id": "Unity", "name": "Rune of Unity", "color": "#ff7850", "where": "Global: bought with Robux in the Shop", "unlock": "Anyone", "rank": 0, "global": True,
     "focus": "Whenever anyone buys Global Runes, every player in the server gets the rolls, and the whole server gets a Rune Rush.",
     "tiers": [["Recruit", 89, {"Credits": 1.25}, 1000, ""], ["Ally", 10, {"RuneLuck": 1.5}, 200, ""], ["Comrade", 0.89, {"Redeploy": 1.5, "Credits": 2}, 30, ""],
               ["Champion", 0.1, {"RuneBulk": 1.5, "Damage": 2}, 5, ""], ["Legend", 0.01, {"Redeploy": 3, "Damage": 3, "Credits": 3}, 1, ""]]},
]
TIER_COLORS = ["#c8d0dc", "#6ee678", "#5aaaff", "#b478ff", "#ff78c8", "#ffc446", "#ff8a3c", "#ff4a5a"]
INDEX_TICKETS = [1, 2, 3, 5, 8, 15, 30, 60]
RUNE_SOURCES = {
    "Luck": ["Rune Luck upgrade: +25% per level in both the Credit tab (15 levels) and the Redeploy tab (15 levels)",
             "Field Command (Command tree): +15% to all rune stats per level",
             "Rune Attunement (Cargo Bay): +25% per level (3 levels)",
             "\"More Luck\" ticket boost: +10% per level", "Rune Luck pass ×1.5 and Luck Potion ×2 (15 min)",
             "Rune Rush ×1.5 for the whole server when someone buys Global Runes",
             "+10% for every altar whose index you complete", "Runes with a Luck bonus (Glimmer, Overdrive, Treasure, Maelstrom, Ally)"],
    "Speed": ["Rune Speed upgrade: +20% per level in the Credit tab and the Redeploy tab", "Field Command: +15% per level",
              "\"More Speed\" ticket boost: +10% per level", "Rune Speed pass ×1.5 and Speed Potion ×2", "Runes with a Speed bonus (Pulse, Jewel, Thunder)"],
    "Bulk": ["Rune Bulk upgrade: +30% per level in the Credit tab and the Redeploy tab", "Field Command: +15% per level",
             "\"More Bulk\" ticket boost: +10% per level", "Rune Bulk pass ×1.5 and Bulk Potion ×2", "Runes with a Bulk bonus (Silver, Mythic, Hoard, Stormborn, Champion)"],
    "Clone": ["Rune Clone pass: +1 (every roll happens twice)"],
}

# --------------------------------------------------------------------------------------------- bots
BOTS = [
    {"id": "Training", "name": "Training Drone", "zone": "Main Hall", "rank": "Unranked", "hp": 50, "armor": 0, "dmg": 3, "credits": 10, "respawn": 2.5,
     "marks": 4, "heat": 9, "scrap": 1, "mxp": 1, "ult": 4, "sxp": 2},
    {"id": "Armored", "name": "Armored Mech", "zone": "Advanced Combat", "rank": "Bronze 3 + 1M gate", "hp": 1000, "armor": 0.10, "dmg": 15, "credits": 100, "respawn": 8,
     "marks": 8, "heat": 16, "scrap": 4, "mxp": 3, "ult": 7, "sxp": 5, "note": "Bulwark's hammer ignores its armor."},
    {"id": "Elite", "name": "Elite Android", "zone": "Elite Combat", "rank": "Bronze 1 + 5B gate", "hp": 10000, "armor": 0.25, "dmg": 5, "credits": 1500, "respawn": 16,
     "marks": 16, "heat": 30, "scrap": 18, "mxp": 10, "ult": 14, "sxp": 15, "note": "Elite Hunter (Redeploy tree) adds up to +1,250% damage against it."},
    {"id": "Sentinel", "name": "Sentinel", "zone": "Sturmfeste Village", "rank": "Silver 5", "hp": 25000, "armor": 0.15, "dmg": 8, "credits": 12000, "respawn": 6,
     "marks": 10, "heat": 12, "scrap": 6, "mxp": 2, "ult": 5, "sxp": 6},
    {"id": "Knight", "name": "Knight", "zone": "Castle Grounds", "rank": "Silver 4", "hp": 90000, "armor": 0.25, "dmg": 18, "credits": 60000, "respawn": 10,
     "marks": 16, "heat": 20, "scrap": 14, "mxp": 5, "ult": 9, "sxp": 12},
    {"id": "Warden", "name": "Warden", "zone": "The Keep", "rank": "Silver 2", "hp": 400000, "armor": 0.35, "dmg": 12, "credits": 350000, "respawn": 20,
     "marks": 28, "heat": 36, "scrap": 40, "mxp": 14, "ult": 16, "sxp": 30, "note": "Warden kills also pay Honor."},
]

# --------------------------------------------------------------------------------------------- objectives
PAYLOADS = [["Main Hall", "Training", "×1"], ["Advanced Combat", "Armored", "×4"], ["Elite Combat", "Elite", "×16"]]
CONTROL_POINTS = [["A", "Main Hall", "Training", "×1", "10 CP"], ["B", "Loading Dock (Advanced Combat)", "Armored", "×5", "50 CP"], ["C", "Apex Ring (Elite Combat)", "Elite", "×25", "250 CP"]]
PUSH_CHECKPOINTS = [["Grounds Courtyard", "Silver 5", 20], ["Gatehouse", "Silver 4", 45], ["Great Hall", "Silver 2", 80], ["Throne Room", "Silver 1", 150]]
PARKOUR = [["Scaffold Sprint", "Village rooftops", 38, 25, "Nothing"], ["Ravine Leap", "Piers to the castle wall", 22, 50, "Double Jump"],
           ["Tower Ascent", "The Lab tower", 35, 90, "Dash + Grapple"]]
RESEARCH = [["Coin Alchemy", "Multiplies all Credits (×1.25 per level)", 10, 40, "5 min"], ["Storm Metallurgy", "Multiplies all damage (×1.2 per level)", 10, 40, "5 min"],
            ["Redeploy Doctrine", "Multiplies Redeploy payouts (×1.2 per level)", 10, 60, "7 min"], ["Siege Engineering", "Siege robot +12% speed per level", 5, 50, "10 min"],
            ["Crown Minting", "+20% Crowns per level", 5, 80, "15 min"], ["Aerodynamics", "+15% Momentum per level", 5, 60, "10 min"],
            ["Field Logistics", "Unlocks Auto-Redeploy", 1, 300, "1 h"], ["Second Workbench", "Research two projects at once", 1, 500, "2 h"],
            ["Ghost Runner", "Every 5 min a ghost re-runs your best parkour times for idle Momentum", 3, 120, "15 min"]]
TRIALS = [["Iron Gauntlet", "Bots hit you 3× harder", "+8% armor per tier"], ["Rationing", "Credit upgrades cost 5×", "−8% Credit upgrade costs per tier"],
          ["Shaky Hands", "Your fire rate is halved", "+8% fire rate per tier"]]
TRAVEL = [["Hero Hub", "Start", "Safe zone: heroes, store and upgrade boards"], ["Main Hall", "Start", "Training bots"], ["Advanced Combat", "Gate", "Armored bots"],
          ["Elite Combat", "Gate", "Elite bots"], ["Firing Range", "Start", "Test your damage on the dummies"], ["Payload", "Bronze 4", "Jump to the Main Hall cart"],
          ["Control Point", "Bronze 2", "Point A in the Main Hall"], ["Sturmhorn Tavern", "Silver 5", "Spawn: boards, heroes and the store"],
          ["Town Square", "Silver 5", "Where the siege robot starts"], ["Stormfield", "Silver 5", "World Boss arena"], ["Castle Grounds", "Silver 4", "The courtyard below the castle"],
          ["Scaffold Sprint", "Silver 4", "Parkour: village rooftops"], ["Ravine Leap", "Silver 4", "Parkour: piers to the castle wall"],
          ["Tower Ascent", "Silver 4", "Parkour: the Lab tower"], ["Research Lab", "Silver 3", "The alchemist's tower"], ["Tourney Yard", "Silver 2", "Trials arena"],
          ["Castle Courtyard", "Silver 2", "Inside the gatehouse"], ["Throne Room", "Silver 1", "The end of the siege"]]

# --------------------------------------------------------------------------------------------- events
WEEKLY = [["RUNES ROLLED", "Runes rolled this week"], ["BOTS DEFEATED", "Bot kills this week"], ["BOSS DAMAGE", "Share of World Boss damage this week"]]
WEEKLY_REWARDS = [["#1", "500 Tickets", "Weekly Champion title"], ["Top 3", "300 Tickets", "Weekly Podium title"], ["Top 10", "150 Tickets", ""],
                  ["Top 25", "80 Tickets", ""], ["Top 100", "40 Tickets", ""]]
HALL = [["TOP HEROES", "Rank progress", ["The Apex", "Ascendant", "Ladder Elite"]], ["RICHEST", "Lifetime Credits", ["Tycoon", "Magnate", "High Roller"]],
        ["BOT SLAYERS", "Bots defeated", ["Annihilator", "Warlord", "Headhunter"]], ["RUNE MASTERS", "Runes rolled", ["Runelord", "Runesage", "Rune Collector"]],
        ["MOST DEVOTED", "Hours played", ["Eternal", "Devoted", "Dedicated"]], ["CROWN BARONS", "Crowns earned", ["Storm King", "Crown Baron", "Crown Holder"]],
        ["BOSS HUNTERS", "World Bosses defeated", ["Colossus Bane", "Stormbreaker Elite", "Boss Hunter"]],
        ["TOP SUPPORTERS", "Robux spent", ["Crown Patron", "Golden Patron", "Top Supporter"]]]
TITLES = {
    "Playtime": [["Fresh Recruit", "1 hour", "Common"], ["Regular", "10 hours", "Rare"], ["Veteran", "50 hours", "Epic"], ["Old Guard", "150 hours", "Legendary"], ["Timeless", "500 hours", "Mythic"]],
    "Bots defeated": [["Bot Buster", "1,000", "Common"], ["Scrapper", "10,000", "Rare"], ["Wrecking Crew", "100,000", "Epic"], ["Machine's End", "1,000,000", "Legendary"],
                      ["Extinction Event", "10,000,000", "Mythic"]],
    "Events": [["Storm Survivor", "Season 1: reach tier 30", "Rare"], ["Storm Baron", "Season 1: tier 10 with the Season Pass", "Epic"],
               ["Seraph of the Storm", "Season 1: tier 20 with the Season Pass", "Epic"], ["Stormbreaker", "Season 1: tier 30 with the Season Pass", "Legendary"],
               ["Weekly Podium", "Top 3 on a weekly board", "Epic"], ["Weekly Champion", "#1 on a weekly board", "Legendary"]],
    "Supporter": [["Supporter", "Any purchase", "Common"], ["Patron", "1,000 Robux", "Rare"], ["Benefactor", "5,000 Robux", "Epic"], ["Hero's Champion", "20,000 Robux", "Legendary"]],
}
RARITY_COLORS = {"Common": "#d7dee8", "Rare": "#5abeff", "Epic": "#be78ff", "Legendary": "#ffc446", "Mythic": "#ff5a78"}
DAILY = [["Day 1", "Credits (4% of your next rank-up cost)"], ["Day 2", "Credits (8%)"], ["Day 3", "Credits (12%) + 50 Cargo"], ["Day 4", "Credits (16%)"],
         ["Day 5", "Credits (20%) + 100 Cargo (+50 Crowns in Silver)"], ["Day 6", "Credits (24%)"], ["Day 7", "Credits (28%) + Redeploy points + a Skin Token"]]

# --------------------------------------------------------------------------------------------- skins + season
SKINS = {
    "Bulwark": [["Obsidian", "Epic", "Volcanic glass, carved with runes.", "#965aff"], ["Gilded Bastion", "Legendary", "A fortress wrapped in gold.", "#ffcd50"]],
    "Anchor": [["Coral Reef", "Epic", "Straight from the brightest reef.", "#ff6e96"], ["Abyssal", "Legendary", "Straight up from the deepest trench.", "#3ce6be"]],
    "Vanguard": [["Jungle Ranger", "Epic", "Woodland camo for the long patrol.", "#789646"], ["Frostline", "Epic", "Arctic-issue armor, cold as the far north.", "#96dcff"],
                 ["Stormbreaker", "Legendary", "Season 1 exclusive: tier 30 of the Season Pass.", "#5aaaff", "S1"]],
    "Flicker": [["Neon Circuit", "Epic", "Blink so fast you leave light trails.", "#ff50c8"], ["Sakura", "Epic", "Blossom-light and twice as fast.", "#ffaad2"]],
    "Havoc": [["Hellfire", "Epic", "Molten cracks and a scorched hood.", "#ff7828"], ["Grave Warden", "Legendary", "Bone, shadow and a ghostly glow.", "#78ff96"]],
    "Longshot": [["Arctic Sniper", "Epic", "Snow camo. You'll never see the shot.", "#c8e1f5"], ["Desert Ghost", "Epic", "Invisible in the dunes.", "#e6be78"]],
    "Kestrel": [["Snow Owl", "Epic", "White feathers over the winter ramparts.", "#dcebff"], ["Phoenix", "Legendary", "Feathers of fire.", "#ff6428"]],
    "Ember": [["Blue Flame", "Epic", "Hotter than orange. Much hotter.", "#50aaff"], ["Jade Dragon", "Legendary", "Dragon scales and dragon fire.", "#3cc88c"]],
    "Rivet": [["Neon Mechanic", "Epic", "Night shift in the neon garage.", "#46d2ff"], ["Scrapyard", "Epic", "Welded together from whatever was lying around.", "#ffa03c"]],
    "Broker": [["Emerald Tycoon", "Epic", "Old money, new pinstripes.", "#3cc86e"], ["High Roller", "Legendary", "The house always wins.", "#ff5a5a"],
               ["Storm Baron", "Epic", "Season 1 exclusive: tier 10 of the Season Pass.", "#468cff", "S1"]],
    "Solace": [["Nightbloom", "Epic", "Moonlit robes and glowing blossoms.", "#be8cff"], ["Sunforged", "Legendary", "Radiant as a summer dawn.", "#ffbe3c"],
               ["Stormward Seraph", "Epic", "Season 1 exclusive: tier 20 of the Season Pass.", "#78c8ff", "S1"]],
    "Vesper": [["Toxic Bloom", "Epic", "Beautiful. Deadly. Probably both.", "#a0ff3c"], ["Crimson Eclipse", "Legendary", "Blood-red robes under a dark sun.", "#e6283c"]],
}
SEASON = {"name": "STORMBREAK", "number": 1, "tagline": "The storm has come to Sturmfeste.", "tiers": 30, "xp_per_tier": 1500, "ends": "2026-12-01", "price": 399}
SEASON_XP = [["World Boss", 500], ["Rune rolls", "1 per 400 runes"], ["Daily reward", 300], ["Payload delivered", 250], ["Payload checkpoint", 100],
             ["Capture completed", 150], ["Siege checkpoint", 150], ["Contract", 120], ["Ticket earned", 60], ["New rune tier (index)", 50],
             ["Kills", "2 (Training) to 30 (Warden)"]]
# tier: free, premium
SEASON_REWARDS = [
    ["5 Tickets", "20 Tickets"], ["Luck Potion", "3 Luck Potions"], ["8 Tickets", "25 Tickets"], ["Credit Potion", "3 Credit Potions"], ["10 Tickets", "Skin Token"],
    ["Speed Potion", "30 Tickets"], ["10 Tickets", "3 Bulk Potions"], ["Bulk Potion", "30 Tickets"], ["12 Tickets", "4 Luck Potions"], ["Skin Token", "Storm Baron skin + title"],
    ["12 Tickets", "4 Credit Potions"], ["2 Luck Potions", "40 Tickets"], ["15 Tickets", "4 Speed Potions"], ["2 Credit Potions", "45 Tickets"], ["15 Tickets", "Skin Token"],
    ["2 Speed Potions", "45 Tickets"], ["18 Tickets", "5 Bulk Potions"], ["2 Bulk Potions", "50 Tickets"], ["18 Tickets", "5 Luck Potions"], ["Skin Token", "Stormward Seraph skin + title"],
    ["20 Tickets", "5 Credit Potions"], ["3 Luck Potions", "60 Tickets"], ["20 Tickets", "5 Speed Potions"], ["3 Credit Potions", "70 Tickets"], ["25 Tickets", "Skin Token"],
    ["3 Speed Potions", "80 Tickets"], ["25 Tickets", "6 Bulk Potions"], ["3 Bulk Potions", "90 Tickets"], ["40 Tickets", "8 Luck Potions"], ["Storm Survivor title", "Stormbreaker skin (Legendary)"],
]

# --------------------------------------------------------------------------------------------- shop (prices in Robux)
PASSES = [
    ["Game Pass Bundle", 1599, "Every pass in the shop except VIP II and III, plus every pass added later.", "PassBundle"],
    ["2× Credits", 199, "Permanently double every Credit from kills.", "Credits"],
    ["2× Redeploy", 199, "Permanently double every Redeploy payout.", "Redeploy"],
    ["2× Cargo", 199, "Permanently double all Cargo.", "Cargo"],
    ["2× Crowns", 249, "Permanently double every Crown from the siege.", "Crowns"],
    ["2× Currency Bundle", 599, "All four 2× passes in one.", "Credits"],
    ["VIP I", 249, "×1.5 damage, fire rate and every currency, double daily rewards and a gold VIP tag.", "HallOfFame"],
    ["VIP II", 799, "×2 damage, fire rate and every currency, plus all VIP I perks (replaces VIP I's boost).", "HallOfFame"],
    ["VIP III", 2499, "×4 damage, fire rate and every currency, plus all VIP perks.", "HallOfFame"],
    ["Rune Luck", 199, "×1.5 rune Luck.", "Pass_RuneLuck"], ["Rune Bulk", 199, "×1.5 rune Bulk.", "Pass_RuneBulk"], ["Rune Speed", 199, "×1.5 rune Speed.", "Pass_RuneSpeed"],
    ["Rune Clone", 299, "+1 Clone: every roll happens one extra time.", "Pass_RuneClone"],
    ["Parkour Kit", 99, "Double Jump + Dash from the very start.", "Momentum"],
    ["Master Researcher", 399, "An extra Research Lab workbench, and every project finishes 25% faster.", "Research"],
]
PRODUCTS = [
    ["Starter Pack", 99, "1 Hero Token + 100 Cargo + 30 min of 2× Credits. One per player."], ["Hero Token", 99, "Unlock any hero right now."],
    ["2× Credits (30 min)", 39, "Stacks with everything; time adds up."], ["Credit Cache", 29, "10% of your next rank-up cost in Credits."],
    ["Credit Vault", 129, "50% of your next rank-up cost in Credits."], ["Crown Pouch", 49, "100–650 Crowns, scaled to your Silver rank."],
    ["Research Rush", 79, "Instantly finish everything on your Lab workbenches."], ["Skin Token", 149, "Unlock any hero skin."],
    ["Season Pass", 399, "The premium track of Season 1 with 3 exclusive skins."], ["+5 Season Tiers", 199, "Jump 5 tiers ahead."],
    ["Global Runes", "19–2,499", "250 to 125K Rune of Unity rolls for everyone in the server, plus a Rune Rush."],
    ["Tickets", "25–9,999", "+10 to +11K Tickets."], ["Potions", 19, "One potion; the Potion Bundle (199) has 5 of each."],
    ["Boost level", 39, "One level of a ticket boost."],
]
BOOSTS = [["More Luck", "+10% rune Luck"], ["More Bulk", "+10% rune Bulk"], ["More Speed", "+10% rune Speed"], ["More Credits", "+5% Credits"], ["More Redeploy", "+5% Redeploy"]]
POTIONS = [["Luck Potion", "×2 rune Luck"], ["Bulk Potion", "×2 rune Bulk"], ["Speed Potion", "×2 rune Speed"], ["Credit Potion", "×2 Credits"]]

# --------------------------------------------------------------------------------------------- guide + tips + faq
GUIDE_STEPS = [
    ["Unranked → Bronze 5 (5K Credits)", "Shoot Training bots in the Main Hall with Vanguard. Put Credits into Damage first, then Fire Rate and Credit Multiplier. Chain kills without getting hit to build On Fire heat (up to 2.5× Credits)."],
    ["Bronze 5: Redeploy + your first hero", "Spend your Hero Token (see the unlock order; Ember is a great first pick). Redeploy whenever the payout has grown a lot: Redeploy Multiplier and Credit Surge in the Redeploy tab double your gains per level, so buy them first."],
    ["Bronze 4: Payload + Cargo Bay", "Escort the Main Hall payload for Cargo. Spend Cargo in the Cargo Bay (C): Supply Drop, Armory Uplink and Priority Shipping. Cargo never resets."],
    ["Bronze 3: Turrets, Mastery, Bounties", "Buy the Advanced Combat gate (1M). Build turrets with Scrap, kill WANTED bots for Bounty Marks, and pick your hero's minor perk at Mastery 2."],
    ["Bronze 2: Runes, capture points, Command", "Stand on the Rune of Fortune in the Armory to roll. Buy Rune Speed, Luck and Bulk in the Credit and Redeploy tabs. Capture points pay CP for the Command tree (N)."],
    ["Bronze 1: Elite Combat + Promotion", "Buy the Elite Combat gate (5B), open the Rune of Valor, then promote to Silver when you can afford 130T Credits. Promotion trades this tier's Redeploy progress for Skill Rating."],
    ["Silver 5 and beyond", "Board the dropship behind the Armory to Sturmfeste: the Siege Push pays Crowns, parkour pays Momentum, the Research Lab runs while you're offline, and the Storm Colossus rises every hour."],
]
TIPS = [
    ["Redeploy", "Redeploy early and often", "Redeploy points compound: the Redeploy Multiplier doubles every payout, so short early runs beat one long one."],
    ["Cargo", "Spend Cargo right away", "Cargo upgrades are permanent and boost every future run."],
    ["OnFire", "Stay On Fire", "Heat multiplies kill Credits up to 2.5×. Taking damage knocks it down, so tanks and healers keep it longest."],
    ["Runes", "Buy rune upgrades", "Rune Speed, Luck and Bulk sit in both the Credit and Redeploy tabs, and Field Command boosts all three."],
    ["Command", "Build one turret", "Building a single turret opens the Command tree's Scrap branch, including the Rune Engine that rolls anywhere."],
    ["Ticket", "Tickets reward playtime", "1 Ticket every 5 minutes in game. Permanent Boosts are the best first buy."],
    ["Research", "Queue research before logging off", "Research timers keep running offline; start the longest project last."],
    ["Group", "Play in a group", "Groups give +10% per member (up to +30%) and share objectives. Friends in the server add the Squad Bonus on top."],
]
FAQ = [
    ["How do I get more heroes in Hero Incremental?", "Every rank up pays one Hero Token, and the promotion to Silver pays another. Spend tokens at the Hero terminal in the Hub (or press H). You start with Vanguard, so the 11 tokens from Bronze 5 to Silver 5 unlock the rest of the roster. Hero Tokens can also be bought in the Store, and the code THANKYOU gives one."],
    ["What should I spend my first Hero Token on?", "Ember is the best first pick: 4× fire rate, a 120-round tank and burn damage suit the crowded Main Hall. Then Bulwark at Bronze 4 for the payload and Broker at Bronze 3 for Credits. See the recommended unlock order on the tier list page."],
    ["What resets when I rank up?", "Credits, Credit upgrades, Redeploy points, the Redeploy tree (except nodes kept by Standing Orders), Scrap and turrets (unless you have Engineers level 2). Cargo, Bounty Marks, CP, SR, runes, heroes, skins and every permanent tree stay."],
    ["What does Redeploy do?", "Redeploy cashes in your Credits for Redeploy points and Rank XP, then resets your Credits and Credit upgrades. RP buy the Redeploy tree, whose Redeploy Multiplier and Credit Surge double your gains per level."],
    ["Do I earn anything while offline?", "No. Credits, Tickets and runes only come in while you're in the game. Research Lab timers are the one exception: they keep counting down while you're away."],
    ["Will I get kicked for being AFK?", "No. The game quietly rejoins you before Roblox's 20-minute idle kick, so you can keep rolling runes or letting payloads creep."],
    ["How do rune altars work?", "Stand on an open altar and it rolls every second. Each rune costs a few Credits (half a Training kill's worth, less with Rune Rations). Every tier you own gives a permanent bonus that grows with your count up to [MAX]. Altars are free and open by rank."],
    ["How do I get to Sturmfeste?", "Reach Silver 5 by promoting from Bronze 1. The back door of the Armory opens onto the dropship pad; board it, or use fast travel (T), to reach the Sturmhorn Tavern."],
    ["When does the World Boss spawn?", "The Storm Colossus rises on the Stormfield at the top of every hour (from Silver 5). You have 5 minutes to bring it down. Everyone who deals at least 1% of its health shares the loot."],
    ["How do I play with friends?", "Open the Menu (V) and choose GROUP to invite up to 3 friends. A group gets +10% per member (up to +30%), shares its own payloads, capture points and siege robot, and splits kill Credits by damage dealt."],
    ["How do I get skins?", "Each skin costs 600 Tickets or one Skin Token. Skin Tokens come from day 7 of the daily streak, Skin Vouchers in the Bounty tab, Season Pass tiers and the Store. Skins are cosmetic only."],
    ["What are codes and where do I redeem them?", "Codes give free rewards. Press X to open the Shop and use the Codes section, or open Settings (gear icon). See the codes page for every working code."],
    ["Is VIP worth it?", "VIP I (249 Robux) gives ×1.5 damage, fire rate and every currency plus double daily rewards. VIP II and III replace it with ×2 and ×4. Only the highest VIP tier applies. Everything else in the game can be earned by playing."],
    ["What is the fastest way to rank up?", "Buy Redeploy Multiplier and Credit Surge every rank, Redeploy often, keep the Rune of Fortune rolling, spend Cargo immediately, and play an S-tier farmer (Broker, Bulwark or Solace). Use the rank-up calculator to plan."],
]

PATCHES = [
    {"tag": "Overhaul", "title": "The big overhaul", "date": "2026-09-26", "items": [
        "The Facility is now three sectors, each with its own payload (×1 / ×4 / ×16 rewards) and capture point (×1 / ×5 / ×25 CP).",
        "Capture points are long holds against defender waves and pay only when they complete, then relock for 2.5 minutes.",
        "New unlock ladder: Turrets at Bronze 3; Runes, capture points and the new Command tree at Bronze 2; Rune of Valor at Bronze 1.",
        "Rune altars are free and open by rank. Rolls cost a few Credits each, and Rune Speed, Luck and Bulk are now upgrades in the Credit and Redeploy tabs.",
        "Command tree (N): rune stats, capture speed and cheaper rolls with CP; a Scrap branch with Rune Engine and Engineers once you build a turret.",
        "Honor Hall (Silver 2) and Tempest Forge (Silver 1) add two more permanent layers.",
        "Layer milestones: your first 10, 100 and 1,000 of a new currency give a free node and ×3 of it for 10 minutes.",
        "Every hero has a passive, and right-click is now alt-fire: aim, scope, or guard for tanks.",
        "Automation is earned in the trees (Quartermaster, Auto-Redeploy, Auto-Capture). New 2× Redeploy, Cargo and Crowns passes, and VIP I–III."]},
    {"tag": "Social", "title": "Groups, Hall of Fame & personal objectives", "date": "2026-09-26", "items": [
        "Groups of up to 4 (MENU > GROUP): +10% per member, up to +30%.",
        "Payloads, capture points and the siege robot are now personal (or shared by your group), so nobody steals your progress.",
        "Kill Credits are split by damage dealt, and assists get paid.",
        "Hall of Fame wing east of the Hub: 8 all-time boards with statues for #1 and titles for the top 10."]},
    {"tag": "Season 1", "title": "Stormbreak", "date": "2026-09-24", "items": [
        "Season Pass with 30 tiers: free and premium tracks, 3 exclusive skins (Storm Baron, Stormward Seraph, Stormbreaker).",
        "27 hero skins, bought with 600 Tickets or a Skin Token.",
        "The Storm Colossus World Boss rises on the Stormfield at the top of every hour.",
        "Weekly boards for runes rolled, bots defeated and boss damage, with Ticket rewards.",
        "Profile (J) with lifetime stats and titles. The AFK guard rejoins you before the idle kick."]},
    {"tag": "Feel", "title": "Effects & polish", "date": "2026-09-26", "items": [
        "New effects for every ability and ultimate, bot deaths, rune pulls and rank ups.",
        "Damage falls off with range for shotguns and SMGs; out-of-combat health regeneration.",
        "Unlock cinematics show off each new system; the dropship flies you to Sturmfeste."]},
    {"tag": "Silver", "title": "Sturmfeste", "date": "2026-09-24", "items": [
        "Silver ranks open Sturmfeste, a storm-lashed castle town with Sentinels, Knights and Wardens.",
        "Siege Push, the Mobility tree and parkour courses, the Research Lab and Trials.",
        "Fast travel (T) and in-game feedback."]},
]
